In [ ]:
'''
Задание 1
Напишите функцию, которая классифицирует фильмы из материалов занятия по правилам:

оценка 2 и ниже — низкий рейтинг;
оценка 4 и ниже — средний рейтинг;
оценка 4.5 и 5 — высокий рейтинг.
Результат классификации запишите в столбец class.

Задание 2
Используйте файл keywords.csv.

Нужно написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определённому региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {

1
2
3
4
5
'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

Результат классификации запишите в отдельный столбец region.
'''

In [ ]:
#Задание 1
import pandas as pd
data=pd.read_csv('ratings.csv', delimiter=',')
data.head()
def raiting_class_simple(some_data):
    ls=[]
    for line in data.rating:
        if line>=4.5:
            ls.append('высокий рейтинг')
        elif 2<line<4.5:
            ls.append('средний рейтинг')
        elif line<=2:
            ls.append('низкий рейтинг')
    data['class']=ls
    #data.loc[100:110]
    return data
    
data2=raiting_class_simple(data)
data2.loc[100:110]

     userId  movieId  rating   timestamp            class
100       3      296     4.5  1298862418  высокий рейтинг
101       3      318     5.0  1298862121  высокий рейтинг
102       3      355     2.5  1298861589  средний рейтинг
103       3      356     5.0  1298862167  высокий рейтинг
104       3      377     2.5  1298923242  средний рейтинг
105       3      527     3.0  1298862528  средний рейтинг
106       3      588     3.0  1298922100  средний рейтинг
107       3      592     3.0  1298923247  средний рейтинг
108       3      593     3.0  1298921840  средний рейтинг
109       3      595     2.0  1298923260   низкий рейтинг
110       3      736     3.5  1298932787  средний рейтинг

In [ ]:
#Задание 2
geo_data = {
'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']}

import pandas as pd
data = pd.read_csv('keywords.csv')
def geo_cl(row):
  if 'москва' in row['keyword'] or 'тула' in row['keyword'] or 'ярославль' in row['keyword']:
    return 'Центр'
  elif 'петербург' in row['keyword'] or 'псков' in row['keyword'] or 'псков' in row['keyword']:
    return 'Северо-Запад'
  elif 'владивосток' in row['keyword'] or 'сахалин' in row['keyword'] or 'хабаровск' in row['keyword']:
    return 'Дальний Восток'
  else:
    return 'undefined'
    
    
data['region'] = data.apply(geo_cl, axis=1)
    
data['region'].value_counts()

undefined         99281
Центр               387
Северо-Запад        238
Дальний Восток       94
Name: region, dtype: int64